import type { Category, MenuItem } from "@/lib/types";

export const categories: Category[] = [
  { id: "popular", name: "Popular", description: "The items customers come back for." },
  { id: "pizza", name: "Pizza", description: "Crown crusts, stuffed crusts, and Heaven specials." },
  { id: "burgers", name: "Burgers", description: "Crispy zingers and loaded chicken burgers." },
  { id: "shawarma", name: "Shawarma", description: "Fresh wraps, cheese shawarma, and platters." },
  { id: "starters", name: "Starters", description: "Rolls, sticks, chunks, wings, and nuggets." },
  { id: "platters", name: "Platters", description: "Big plates built for sharing." },
  { id: "fries", name: "Fries & Sides", description: "Loaded fries, regular fries, and fried chicken." },
  { id: "drinks", name: "Drinks", description: "Cold soft drinks for every order." },
];

const pizzaAddOns = [
  { id: "mayo-sauce", name: "Mayo sauce", price: 70 },
  { id: "small-extra-topping", name: "Small extra topping", price: 100 },
  { id: "medium-extra-topping", name: "Medium extra topping", price: 120 },
  { id: "large-extra-topping", name: "Large extra topping", price: 180 },
];

const burgerAddOns = [
  { id: "extra-cheese", name: "Extra cheese", price: 90 },
  { id: "extra-sauce", name: "Extra sauce", price: 50 },
  { id: "extra-patty", name: "Extra patty", price: 220 },
];

const sideAddOns = [
  { id: "extra-dip", name: "Extra dip", price: 50 },
  { id: "extra-fries", name: "Extra fries", price: 120 },
  { id: "extra-cheese-sauce", name: "Extra cheese sauce", price: 90 },
];

export const menuItems: MenuItem[] = [
  {
    id: "heaven-crown-crust-pizza",
    categoryId: "pizza",
    name: "Heaven Crown Crust Pizza",
    description: "Crown crust pizza loaded with chicken tikka, fajita, liver, tandoori, supreme, mushroom, and house sauces. From 9 inch.",
    price: 1300,
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=900&q=82",
    tags: ["Crown crust", "Pizza"],
    addOns: pizzaAddOns,
    isPopular: true,
  },
  {
    id: "heaven-stuff-crust-pizza",
    categoryId: "pizza",
    name: "Heaven Stuff Crust Pizza",
    description: "Stuffed crust pizza with melted cheese edges and your choice of signature chicken flavours. From 9 inch.",
    price: 1300,
    image: "https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&w=900&q=82",
    tags: ["Stuff crust"],
    addOns: pizzaAddOns,
    isPopular: true,
  },
  {
    id: "heaven-treat-pizza",
    categoryId: "pizza",
    name: "Heaven Treat Pizza",
    description: "Cheezy tikka, Heaven special, chicken extreme, and behari kabab flavours baked hot.",
    price: 1300,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=82",
    tags: ["Family favourite"],
    addOns: pizzaAddOns,
  },
  {
    id: "heaven-scooper",
    categoryId: "pizza",
    name: "Heaven Scooper",
    description: "Small scooper pizza made for quick cravings, available from 6 inch up to party size.",
    price: 500,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=82",
    tags: ["Quick bite"],
    addOns: pizzaAddOns,
  },
  {
    id: "crunchy-chicken-pasta",
    categoryId: "pizza",
    name: "Crunchy Chicken Pasta",
    description: "Macaroni pasta in white sauce topped with crispy chicken and cheese.",
    price: 800,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=82",
    tags: ["Pasta"],
    addOns: sideAddOns,
  },
  {
    id: "zinger-burger",
    categoryId: "burgers",
    name: "Zinger Burger",
    description: "Crunchy chicken fillet, lettuce, mayo, and a soft toasted bun.",
    price: 430,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=82",
    tags: ["Crispy"],
    addOns: burgerAddOns,
    isPopular: true,
  },
  {
    id: "zinger-supreme",
    categoryId: "burgers",
    name: "Zinger Supreme",
    description: "A richer zinger build with extra sauce, cheese, and a bigger crunch.",
    price: 650,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=900&q=82",
    tags: ["Supreme"],
    addOns: burgerAddOns,
    isPopular: true,
  },
  {
    id: "tower-burger",
    categoryId: "burgers",
    name: "Tower Burger",
    description: "Tall, saucy, and stacked with crispy chicken for a proper meal.",
    price: 600,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=82",
    tags: ["Loaded"],
    addOns: burgerAddOns,
  },
  {
    id: "chicken-burger",
    categoryId: "burgers",
    name: "Chicken Burger",
    description: "Simple, fresh chicken burger with sauce and salad for everyday cravings.",
    price: 280,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=900&q=82",
    tags: ["Classic"],
    addOns: burgerAddOns,
  },
  {
    id: "chicken-shawarma",
    categoryId: "shawarma",
    name: "Chicken Shawarma",
    description: "Fresh chicken, garlic sauce, salad, and soft wrap toasted on order.",
    price: 200,
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=82",
    tags: ["Value"],
    addOns: burgerAddOns,
    isPopular: true,
  },
  {
    id: "chicken-cheese-shawarma",
    categoryId: "shawarma",
    name: "Chicken Cheese Shawarma",
    description: "Classic shawarma upgraded with creamy cheese and extra house sauce.",
    price: 270,
    image: "https://images.unsplash.com/photo-1662116765994-1e4200c43589?auto=format&fit=crop&w=900&q=82",
    tags: ["Cheesy"],
    addOns: burgerAddOns,
  },
  {
    id: "zinger-shawarma",
    categoryId: "shawarma",
    name: "Zinger Shawarma",
    description: "Crispy zinger strips wrapped with sauce, salad, and a toasted finish.",
    price: 400,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=900&q=82",
    tags: ["Crispy"],
    addOns: burgerAddOns,
  },
  {
    id: "heaven-special-shawarma",
    categoryId: "shawarma",
    name: "Heaven Special Shawarma",
    description: "A bigger, saucier house shawarma made with the Flavour Heaven mix.",
    price: 350,
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=900&q=82",
    tags: ["House special"],
    addOns: burgerAddOns,
    isPopular: true,
  },
  {
    id: "platter-shawarma",
    categoryId: "shawarma",
    name: "Platter Shawarma",
    description: "Shawarma served open with fries, sauces, and a filling plate portion.",
    price: 500,
    image: "https://images.unsplash.com/photo-1644364935906-792b2245a2c0?auto=format&fit=crop&w=900&q=82",
    tags: ["Platter"],
    addOns: sideAddOns,
  },
  {
    id: "heaven-rolls",
    categoryId: "starters",
    name: "Heaven Rolls",
    description: "Four rolls stuffed with yummy sauces and savoury fillings.",
    price: 600,
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=82",
    tags: ["4 pcs"],
    addOns: sideAddOns,
  },
  {
    id: "heaven-sticks",
    categoryId: "starters",
    name: "Heaven Sticks",
    description: "Fresh baked bread sticks filled with the yummiest cheese blend.",
    price: 500,
    image: "https://images.unsplash.com/photo-1619535860434-cf9b8045f4bb?auto=format&fit=crop&w=900&q=82",
    tags: ["Cheese"],
    addOns: sideAddOns,
  },
  {
    id: "calzone-chunks",
    categoryId: "starters",
    name: "Calzone Chunks",
    description: "Four stuffed calzone chunks served with sauce and fries.",
    price: 950,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=82",
    tags: ["4 pcs"],
    addOns: sideAddOns,
  },
  {
    id: "chicken-nuggets",
    categoryId: "starters",
    name: "Chicken Nuggets",
    description: "Crispy nuggets served hot. Start with 5 pieces or make it 10.",
    price: 350,
    image: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=82",
    tags: ["5 pcs"],
    addOns: sideAddOns,
  },
  {
    id: "oven-baked-wings",
    categoryId: "starters",
    name: "Oven Baked Wings",
    description: "Fresh oven baked wings served with dip sauce. From 6 pieces.",
    price: 450,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=82",
    tags: ["Wings"],
    addOns: sideAddOns,
  },
  {
    id: "flaming-wings",
    categoryId: "starters",
    name: "Flaming Wings",
    description: "Fresh oven baked wings tossed in hot peri peri sauce and served with dip.",
    price: 500,
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=900&q=82",
    tags: ["Spicy"],
    addOns: sideAddOns,
    isPopular: true,
  },
  {
    id: "special-roasted-platter",
    categoryId: "platters",
    name: "Special Roasted Platter",
    description: "Behari spin rolls, wings, fries, and dip sauce built for sharing.",
    price: 1000,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=82",
    tags: ["Shareable"],
    addOns: sideAddOns,
  },
  {
    id: "classic-roll-platter",
    categoryId: "platters",
    name: "Classic Roll Platter",
    description: "Behari rolls and Arabic rolls served with fries and sauce.",
    price: 1000,
    image: "https://images.unsplash.com/photo-1515669097368-22e68427d265?auto=format&fit=crop&w=900&q=82",
    tags: ["Classic"],
    addOns: sideAddOns,
  },
  {
    id: "heaven-sandwich",
    categoryId: "platters",
    name: "Heaven Sandwich",
    description: "Two flavour sandwich with Euro and Mexican notes, grilled and saucy.",
    price: 800,
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=82",
    tags: ["Two flavours"],
    addOns: burgerAddOns,
  },
  {
    id: "pizza-stacker",
    categoryId: "platters",
    name: "Pizza Stacker",
    description: "A stacked, cheesy pizza sandwich style build for heavy cravings.",
    price: 800,
    image: "https://images.unsplash.com/photo-1613564834361-9436948817d1?auto=format&fit=crop&w=900&q=82",
    tags: ["Stacked"],
    addOns: pizzaAddOns,
  },
  {
    id: "fried-chicken",
    categoryId: "fries",
    name: "Fried Chicken",
    description: "Crispy fried chicken, available as one choice piece or a 3 piece meal.",
    price: 270,
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?auto=format&fit=crop&w=900&q=82",
    tags: ["Crispy"],
    addOns: sideAddOns,
  },
  {
    id: "hot-wings",
    categoryId: "fries",
    name: "Hot Wings",
    description: "Classic hot wings with a spicy kick. From 6 pieces.",
    price: 400,
    image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=900&q=82",
    tags: ["Hot"],
    addOns: sideAddOns,
  },
  {
    id: "loaded-fries",
    categoryId: "fries",
    name: "Loaded Fries",
    description: "Fries loaded with sauces, cheese, and flavourful toppings.",
    price: 750,
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=82",
    tags: ["Loaded"],
    addOns: sideAddOns,
    isPopular: true,
  },
  {
    id: "regular-fries",
    categoryId: "fries",
    name: "Regular Fries",
    description: "Crispy fries, salted and served fresh. Regular and large options available.",
    price: 200,
    image: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=900&q=82",
    tags: ["Side"],
    addOns: sideAddOns,
  },
  {
    id: "soft-drink",
    categoryId: "drinks",
    name: "Soft Drink",
    description: "Chilled soft drink. Regular, 500ml, 1 litre, and 1.5 litre sizes available.",
    price: 100,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=900&q=82",
    tags: ["Cold"],
    addOns: [],
  },
];

export const deliveryAreas = [
  { id: "e-11-3", label: "E-11/3 Markaz", fee: 0, eta: "25-35 min" },
  { id: "e-11-2", label: "E-11/2", fee: 0, eta: "30-40 min" },
  { id: "e-11-1", label: "E-11/1", fee: 0, eta: "30-40 min" },
  { id: "e-11-4", label: "E-11/4", fee: 0, eta: "30-40 min" },
  { id: "f-11", label: "F-11", fee: 180, eta: "35-45 min" },
  { id: "g-11", label: "G-11", fee: 180, eta: "35-45 min" },
  { id: "d-12", label: "D-12", fee: 220, eta: "40-50 min" },
];
